language: rust
cache: cargo
script:
  - cargo fmt --all -- --check
  - cargo build --verbose --all
  - cargo test --verbose --all
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
install:
  - (cargo install rustfmt || true)
  - PATH=$PATH:/home/travis/.cargo/bin
